### ISSUE TITLE
Deployment of Legend leads to SDLC always saying "Unauthorized"

### ISSUE THREAD

**Issue by aznashwan** [finos/legend#463]
## Juju deployment of Legend leads to SDLC always saying "Unauthorized"

I'm currently working on [deploying Legend on K8s using Juju operators](https://github.com/canonical/finos-legend-bundle).

Our aim from the start was to provide as close to a 1:1 replica of the "official" deployment steps outlined [here](https://github.com/finos/legend/tree/master/installers/docker-compose/legend).

## Symptom:

Upon deployment and logging into Studio for the first time for the initial setup, *after* being redirected to GitLab and then back to Studio, the Studio simply throws an alert which says "Unauthorized".

The error is from the SDLC and the following log line is present when the request comes in:
`2021-09-29T20:31:02.843Z [sdlc] 192.168.1.104 - - [29/Sep/2021:20:31:02 +0000] "GET /api/currentUser HTTP/1.1" 401 90 "http://10.1.252.88:8080/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:92.0) Gecko/20100101 Firefox/92.0" 15`

Please find the full logs attached as file
[legend-juju-unauthorized-sdlc.log](https://github.com/finos/legend/files/7259904/legend-juju-unauthorized-sdlc.log)

## Configuration:

* we use the images from the `2021-08-17` image releases found [here](https://legend.finos.org/releases)
* all the three services (plus Mongo) are running in dedicated K8s pods with network access between each-other
* the GitLab was deployed directly using the docker-compose templates here](https://github.com/finos/legend/tree/master/installers/docker-compose/legend).
* I can assure you this is NOT a certificate/GitLab app issue (we properly set those up exactly like the docker-compose setup does)

SDLC:
```yaml
applicationName: Legend SDLC
filterPriorities:
  CORS: 4
  GitLab: 1
  org.pac4j.j2e.filter.CallbackFilter: 2
  org.pac4j.j2e.filter.SecurityFilter: 3
gitLab:
  newProjectVisibility: public
  projectTag: legend
  uat:
    app:
      id: 9d1572c0ac20307c8b0ac3ce0a67c0f2c9df53bd3f33a9602d63c07114006e9a
      redirectURI: http://10.1.134.122:7070/api/auth/callback
      secret: f2f0dd435cbda90990c1cba48ab02d43a68dfeec5ff3801ad3309cbde8664543
    server:
      host: 172.16.16.8:6443
      scheme: https
logging:
  appenders:
  - logFormat: '%d{yyyy-MM-dd HH:mm:ss.SSS} %-5p [%thread] %c - %m%n'
    type: console
  level: INFO
pac4j:
  bypassPaths:
  - /api/info
  callbackPrefix: /api/pac4j/login
  clients:
  - org.finos.legend.server.pac4j.gitlab.GitlabClient:
      clientId: 9d1572c0ac20307c8b0ac3ce0a67c0f2c9df53bd3f33a9602d63c07114006e9a
      discoveryUri: https://172.16.16.8:6443/.well-known/openid-configuration
      name: gitlab
      scope: openid profile api
      secret: f2f0dd435cbda90990c1cba48ab02d43a68dfeec5ff3801ad3309cbde8664543
  mongoDb: db-1-0ccd9976-2709-448e-9c1e-75479be4faa7
  mongoSession:
    collection: userSessions
    enabled: true
  mongoUri: mongodb://user-1:fu38x40OleropK2L@mongodb-k8s-0.mongodb-k8s-endpoints:27017
projectStructure:
  extensionProvider:
    org.finos.legend.sdlc.server.gitlab.finos.FinosGitlabProjectStructureExtensionProvider: {}
  projectCreation:
    groupIdPattern: ^org\.finos\.legend\..+
server:
  adminConnectors:
  - port: 7076
    type: http
  applicationConnectors:
  - maxRequestHeaderSize: 128KiB
    port: 7070
    type: http
  gzip:
    includedMethods:
    - GET
    - POST
  requestLog:
    appenders:
    - logFormat: 'OFF'
      type: console
    level: 'OFF'
    type: classic
  rootPath: /api
swagger:
  resourcePackage: org.finos.legend.sdlc.server.resources
  schemes: []
  title: Legend SDLC
  version: local-snapshot
```

Engine:
```yaml
{
    "deployment": {
        "mode": "TEST_IGNORE_FUNCTION_MATCH"
    },
    "logging": {
        "level": "INFO",
        "loggers": {
            "root": {
                "level": "INFO"
            },
            "org.pac4j": {
                "level": "DEBUG"
            }
        },
        "appenders": [
            {
                "type": "console",
                "logFormat": "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5p [%thread] %c - %m%n"
            }
        ]
    },
    "pac4j": {
        "callbackPrefix": "",
        "mongoUri": "mongodb://user-1:fu38x40OleropK2L@mongodb-k8s-0.mongodb-k8s-endpoints:27017",
        "mongoDb": "db-1-0ccd9976-2709-448e-9c1e-75479be4faa7",
        "bypassPaths": [
            "/api/server/v1/info"
        ],
        "clients": [
            {
                "org.finos.legend.server.pac4j.gitlab.GitlabClient": {
                    "name": "gitlab",
                    "clientId": "9d1572c0ac20307c8b0ac3ce0a67c0f2c9df53bd3f33a9602d63c07114006e9a",
                    "secret": "f2f0dd435cbda90990c1cba48ab02d43a68dfeec5ff3801ad3309cbde8664543",
                    "discoveryUri": "https://172.16.16.8:6443/.well-known/openid-configuration",
                    "scope": "openid profile api"
                }
            }
        ],
        "mongoSession": {
            "enabled": true,
            "collection": "userSessions"
        }
    },
    "opentracing": {
        "elastic": "",
        "zipkin": "",
        "uri": "",
        "authenticator": {
            "principal": "",
            "keytab": ""
        }
    },
    "swagger": {
        "title": "Legend Engine",
        "resourcePackage": "org.finos.legend",
        "uriPrefix": "/api"
    },
    "server": {
        "type": "simple",
        "applicationContextPath": "/",
        "adminContextPath": "/admin",
        "requestLog": {
            "appenders": []
        },
        "connector": {
            "maxRequestHeaderSize": "32KiB",
            "type": "http",
            "port": 6060
        }
    },
    "metadataserver": {
        "pure": {
            "host": "127.0.0.1",
            "port": 8090
        }
    },
    "vaults": []
}
```

Studio HTTP config:
```yaml
{
    "uiPath": "/studio",
    "html5Router": true,
    "server": {
        "type": "simple",
        "applicationContextPath": "/",
        "adminContextPath": "/studio/admin",
        "connector": {
            "type": "http",
            "port": 8080
        }
    },
    "logging": {
        "level": "INFO",
        "loggers": {
            "root": {
                "level": "INFO"
            },
            "org.pac4j": {
                "level": "DEBUG"
            }
        },
        "appenders": [
            {
                "type": "console"
            }
        ]
    },
    "pac4j": {
        "callbackPrefix": "/studio/log.in",
        "bypassPaths": [
            "/studio/admin/healthcheck"
        ],
        "mongoUri": "mongodb://user-1:fu38x40OleropK2L@mongodb-k8s-0.mongodb-k8s-endpoints:27017",
        "mongoDb": "db-1-0ccd9976-2709-448e-9c1e-75479be4faa7",
        "clients": [
            {
                "org.finos.legend.server.pac4j.gitlab.GitlabClient": {
                    "name": "gitlab",
                    "clientId": "9d1572c0ac20307c8b0ac3ce0a67c0f2c9df53bd3f33a9602d63c07114006e9a",
                    "secret": "f2f0dd435cbda90990c1cba48ab02d43a68dfeec5ff3801ad3309cbde8664543",
                    "discoveryUri": "https://172.16.16.8:6443/.well-known/openid-configuration",
                    "scope": "openid profile api"
                }
            }
        ],
        "mongoSession": {
            "enabled": true,
            "collection": "userSessions"
        }
    },
    "routerExemptPaths": [
        "/editor.worker.js",
        "/json.worker.js",
        "/editor.worker.js.map",
        "/json.worker.js.map",
        "/version.json",
        "/config.json",
        "/favicon.ico",
        "/static"
    ],
    "localAssetPaths": {
        "/studio/config.json": "/ui-config.json"
    }
}
```

Studio UI config:
```yaml
{
    "appName": "studio",
    "env": "test",
    "sdlc": {
        "url": "http://10.1.134.122:7070/api"
    },
    "metadata": {
        "url": "__LEGEND_DEPOT_URL__/api"
    },
    "engine": {
        "url": "http://10.1.134.68:6060/api"
    },
    "documentation": {
        "url": "https://legend.finos.org"
    },
    "options": {
        "core": {
            "TEMPORARY__disableServiceRegistration": true
        }
    }
}
```
